### ISSUE TITLE
some questions In function of confidence_based_inlier_selection

### ISSUE THREAD

**Issue by xingfuhoumei** [cavalli1234/AdaLAM#9]
-   Thank you very much for your article and code. You have provided me a great help on outlier filtering. I have read every line of your code and thesis thoughts. Both the idea and the code are extremely good I have seen,but I have a little doubt about the function of confidence_based_inlier_selection in ransac.py.
-   The question is about Code on line 43 in ransac.py(  _, inv_indices, res_dup_counts = torch.unique_consecutive(sorted_res_sqr.half().float(), dim=1, return_counts=True, return_inverse=True)
-   I guess you want to delete duplicate value in order to prevent this duplicate value to disorder find inliers in uniformly scattered outliers(maybe my English is hard to understand because i am a Chinese...i'm so sorry about it QAQ）for example，after computing of residuals，i got the value of  residuals :(0.0000e+00, 0.0000e+00, 0.0000e+00, 1.9729e-05, 7.6246e-04, 1.8478e-02). in order to equip the real residual with construct continuous residuals,i must to delete the value (0.0000e+00, 0.0000e+00, 0.0000e+00),so i can guarantee the rest of values can continuous growth?
-  But i find ,in each iteration of  128 iterations，they both user the same index we find duplicate value in  first iteration ，but  i think each iteration have different values，so their index of duplicate value must be different. Unless the offset of these values in xamples is very small so no matter which A can make its residual very littel?
-  I'm so confused about it, so i want to ask for you ,really bother you very much！

**Comment by cavalli1234** [comment]
Hi @xingfuhoumei, thanks for your observations! The one you spotted is an actual issue to in my to-do list for future fixes.

This line you mention is indeed meant to count duplicates, so that I can later re-weight their statistics to better conform to the uniform-outliers assumption. This becomes necessary as some detectors can output the same exact keypoint twice with multiple descriptors (this happens e.g. in some implementations of SIFT when the orientation of a patch is ambiguous). However, the duplicate-finding procedure in the current code is not doing exactly its job and needs fixing as soon as I can find time for it.

For the 0-error residuals, these are due to fitting the affine model to these points exactly. As their error is not statistically significant, their contribution is removed from the counts later ( line 47, https://github.com/cavalli1234/AdaLAM/blob/master/adalam/ransac.py )

So thanks a lot again for spotting this!

**Comment by xingfuhoumei** [comment]
Thank you very much for your reply！This algorithm is the best I have ever seen on outlier filtering field. I made 61 sets of experimental pictures（include GMS、Ratio-test、Brute Force、RANSAC), adalam is far superior to other algorithms in almost every experiment! Let me learn a lot，Whether GPU-based computing algorithm, or algorithms wonderful idea！I‘ll follow you ~ Looking forward to your new ideas~really really appreciate you！
